#!/usr/bin/env python3
"""Aggregate per-case invocation files into a single index.

Reads every `<case_id>.md` under `subagents/<sub-agent>/invocations/`,
extracts the YAML frontmatter, and writes a compact index table to
`subagents/<sub-agent>/invocations_log.md`.

Per `subagents/README.md`: per-case files are the source of truth; the
aggregate is regeneratable. Hand-editing the aggregate is forbidden.

Usage:
    python3 tools/build_invocations_log.py subagents/adversary-review/
    python3 tools/build_invocations_log.py subagents/file-issue/

Run nightly via cron + on demand (any tools/file_issues.py --via-skill
invocation triggers a rebuild before lookup).

Requires Python 3.9+.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

if sys.version_info < (3, 9):
    sys.exit("ERROR: build_invocations_log.py requires Python 3.9+")


def parse_frontmatter(path: Path) -> dict[str, str]:
    """Extract YAML-ish frontmatter (between --- markers) as a flat dict.

    Not a full YAML parser — handles only `key: value` lines, quoted strings,
    and the closing `---`. Sufficient for our schema.
    """
    text = path.read_text()
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}
    block = text[4:end]
    fields: dict[str, str] = {}
    for line in block.splitlines():
        m = re.match(r"^([a-z0-9_]+):\s*(.+)$", line.strip())
        if not m:
            continue
        key = m.group(1)
        val = m.group(2).strip()
        # Strip surrounding quotes
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        fields[key] = val
    return fields


def build_index(subagent_dir: Path) -> str:
    """Build the aggregated invocations_log.md content for a sub-agent dir."""
    invocations_dir = subagent_dir / "invocations"
    if not invocations_dir.is_dir():
        sys.exit(f"ERROR: {invocations_dir} not found")

    case_files = sorted(invocations_dir.glob("*.md"))
    sub_name = subagent_dir.name

    lines = [
        f"# {sub_name} — invocations index",
        "",
        f"**Generated by `tools/build_invocations_log.py`. Do not hand-edit.**",
        f"**Source of truth: `subagents/{sub_name}/invocations/<case_id>.md`** (one file per invocation).",
        "",
        f"Last regenerated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"Total invocations: {len(case_files)}",
        "",
        "## Index",
        "",
        "| case_id | date_utc | trigger / target | verdict | output_sha256 |",
        "|---|---|---|---|---|",
    ]

    verdicts: dict[str, int] = {}
    for f in case_files:
        fields = parse_frontmatter(f)
        case_id = fields.get("case_id", f.stem)
        date_utc = fields.get("date_utc", "?")
        # Sub-agents have different "what was reviewed" fields; pick by what's present
        trigger_or_target = fields.get("trigger") or fields.get("target_repo", "?")
        # Truncate if very long
        if len(trigger_or_target) > 60:
            trigger_or_target = trigger_or_target[:57] + "..."
        verdict = fields.get("verdict") or fields.get("mode_a_verdict", "?")
        verdicts[verdict] = verdicts.get(verdict, 0) + 1
        sha = fields.get("output_sha256") or fields.get("mode_b_sha256", "")
        sha_short = sha[:12] + "..." if len(sha) > 12 else sha
        lines.append(
            f"| [{case_id}](invocations/{f.name}) | {date_utc} | "
            f"{trigger_or_target} | {verdict} | `{sha_short}` |"
        )

    lines.append("")
    lines.append("## Stats")
    lines.append("")
    lines.append(f"- Total invocations: {len(case_files)}")
    if verdicts:
        lines.append("- Verdict distribution:")
        for v, n in sorted(verdicts.items()):
            lines.append(f"  - `{v}`: {n}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("subagent_dir", nargs="?", type=Path,
                        help="Path to subagents/<name>/ directory. "
                             "If omitted, rebuild ALL subagents/*/.")
    args = parser.parse_args()

    if args.subagent_dir:
        targets = [args.subagent_dir]
    else:
        repo_root = Path(__file__).resolve().parent.parent
        targets = sorted(p for p in (repo_root / "subagents").iterdir()
                         if p.is_dir() and (p / "invocations").is_dir())

    for t in targets:
        out_path = t / "invocations_log.md"
        content = build_index(t)
        out_path.write_text(content)
        n = sum(1 for _ in (t / "invocations").glob("*.md"))
        print(f"Wrote {out_path} ({n} invocations indexed)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
