#!/usr/bin/env python3
"""Aggregate per-case invocation files into a single index.

Reads every `<case_id>.md` under `subagents/<sub-agent>/invocations/`,
extracts the YAML frontmatter, and writes a compact index table to
`subagents/<sub-agent>/invocations_log.md`.

Per `subagents/README.md`: per-case files are the source of truth; the
aggregate is regeneratable. Hand-editing the aggregate is forbidden.

Usage:
    python3 tools/build_invocations_log.py subagents/adversary-review/
    python3 tools/build_invocations_log.py subagents/file-issue/

Run nightly via cron + on demand (any tools/file_issues.py --via-skill
invocation triggers a rebuild before lookup).

Requires Python 3.9+.
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

if sys.version_info < (3, 9):
    sys.exit("ERROR: build_invocations_log.py requires Python 3.9+")


def parse_frontmatter(path: Path) -> tuple[dict[str, str], list[str]]:
    """Extract YAML-ish frontmatter (between --- markers) as a flat dict.

    Not a full YAML parser — handles only `key: value` lines, quoted strings,
    and the closing `---`. Sufficient for our schema.

    Returns (fields, warnings). `warnings` is a list of human-readable issues
    (empty if file is well-formed). Per adversary impl-review gap #5: silent
    `{}` on malformed input was the failure mode.
    """
    warnings: list[str] = []
    text = path.read_text()
    if not text.startswith("---\n"):
        warnings.append(f"{path}: missing leading `---\\n` (no YAML frontmatter)")
        return {}, warnings
    end = text.find("\n---\n", 4)
    if end < 0:
        warnings.append(f"{path}: frontmatter not closed (no trailing `---`)")
        return {}, warnings
    block = text[4:end]
    fields: dict[str, str] = {}
    for line in block.splitlines():
        m = re.match(r"^([a-z0-9_]+):\s*(.+)$", line.strip())
        if not m:
            continue
        key = m.group(1)
        val = m.group(2).strip()
        # Strip surrounding quotes
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        fields[key] = val
    return fields, warnings


def build_index(subagent_dir: Path, strict: bool = False) -> tuple[str, list[str]]:
    """Build the aggregated invocations_log.md content for a sub-agent dir.

    Returns (content, all_warnings). If `strict` is True, any per-case-file
    warning causes the function to raise after building the index.
    """
    invocations_dir = subagent_dir / "invocations"
    if not invocations_dir.is_dir():
        sys.exit(f"ERROR: {invocations_dir} not found")

    case_files = sorted(invocations_dir.glob("*.md"))
    sub_name = subagent_dir.name
    all_warnings: list[str] = []

    lines = [
        f"# {sub_name} — invocations index",
        "",
        f"**Generated by `tools/build_invocations_log.py`. Do not hand-edit.**",
        f"**Source of truth: `subagents/{sub_name}/invocations/<case_id>.md`** (one file per invocation).",
        "",
        f"Last regenerated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"Total invocations: {len(case_files)}",
        "",
        "## Index",
        "",
        "| case_id | date_utc | trigger / target | verdict | output_sha256 |",
        "|---|---|---|---|---|",
    ]

    # Required fields whose absence is a per-file warning (not a parse error).
    REQUIRED_FIELDS = ("case_id", "date_utc")
    # At least ONE of these must be present (different sub-agents use different keys).
    EITHER_FIELDS = (("verdict", "mode_a_verdict"), ("output_sha256", "mode_b_sha256"))

    verdicts: dict[str, int] = {}
    for f in case_files:
        fields, warns = parse_frontmatter(f)
        all_warnings.extend(warns)
        # Per-file required-field check (gap #5)
        missing = [k for k in REQUIRED_FIELDS if k not in fields]
        for either in EITHER_FIELDS:
            if not any(k in fields for k in either):
                missing.append("|".join(either))
        if missing:
            all_warnings.append(f"{f}: missing fields {missing}")
        case_id = fields.get("case_id", f.stem)
        date_utc = fields.get("date_utc", "?")
        # Sub-agents have different "what was reviewed" fields; pick by what's present
        trigger_or_target = fields.get("trigger") or fields.get("target_repo", "?")
        # Truncate if very long
        if len(trigger_or_target) > 60:
            trigger_or_target = trigger_or_target[:57] + "..."
        verdict = fields.get("verdict") or fields.get("mode_a_verdict", "?")
        verdicts[verdict] = verdicts.get(verdict, 0) + 1
        sha = fields.get("output_sha256") or fields.get("mode_b_sha256", "")
        sha_short = sha[:12] + "..." if len(sha) > 12 else sha
        lines.append(
            f"| [{case_id}](invocations/{f.name}) | {date_utc} | "
            f"{trigger_or_target} | {verdict} | `{sha_short}` |"
        )

    lines.append("")
    lines.append("## Stats")
    lines.append("")
    lines.append(f"- Total invocations: {len(case_files)}")
    if verdicts:
        lines.append("- Verdict distribution:")
        for v, n in sorted(verdicts.items()):
            lines.append(f"  - `{v}`: {n}")
    lines.append("")

    return "\n".join(lines) + "\n", all_warnings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("subagent_dir", nargs="?", type=Path,
                        help="Path to subagents/<name>/ directory. "
                             "If omitted, rebuild ALL subagents/*/.")
    parser.add_argument("--strict", action="store_true",
                        help="Exit non-zero if any per-case file is malformed "
                             "or missing required fields. Use in pre-commit hooks.")
    args = parser.parse_args()

    if args.subagent_dir:
        targets = [args.subagent_dir]
    else:
        repo_root = Path(__file__).resolve().parent.parent
        targets = sorted(p for p in (repo_root / "subagents").iterdir()
                         if p.is_dir() and (p / "invocations").is_dir())

    total_warnings = 0
    for t in targets:
        out_path = t / "invocations_log.md"
        content, warnings = build_index(t, strict=args.strict)
        out_path.write_text(content)
        n = sum(1 for _ in (t / "invocations").glob("*.md"))
        print(f"Wrote {out_path} ({n} invocations indexed)")
        for w in warnings:
            print(f"  WARNING: {w}", file=sys.stderr)
        total_warnings += len(warnings)

    if args.strict and total_warnings > 0:
        print(f"FAIL (--strict): {total_warnings} warning(s) across all subagents",
              file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
