#!/usr/bin/env python3
"""Derive launch commands (gate / sample / full) from one experiment config.

Codifies the gate → sample → full launch sequence as deterministic
transformations of a single source config. Eliminates drift between stages by
construction: every stage uses the SAME flags as the full launch except for
cohort sub-sample size + output dir.

Anti-pattern this exists to prevent (per local CLAUDE.md "Approval-Triggered
Action Discipline" + 2026-05-07 generic-gate-false-confidence reflection):
hand-typing a "customized gate" config that diverges from the planned full
launch (different stack, workers, modes, or missing flags). The derived
commands are mechanically guaranteed to match.

Usage:
    # Validate first
    tools/derive_sweep_commands.py <config> --stage <gate|sample|full> --validate

    # Print bash to stdout (don't run)
    tools/derive_sweep_commands.py <config> --stage <gate|sample|full> --emit

    # Run directly
    tools/derive_sweep_commands.py <config> --stage <gate|sample|full> --run

Stage semantics:
    gate   — sub-sample 5 models from original cohort, deterministic seed.
             ~5 min compute. Catches launch-path bugs (modellibs injection,
             flag wiring, harness runtime) before larger commitment.
    sample — sub-sample 20 models. ~15-30 min. Catches cohort/stack issues
             at moderate cost before full sweep.
    full   — original cohort. Hours of compute. Only after gate + sample pass.

Sub-sample uses run_experiment.py's existing `models.source: "sample"` with
deterministic seed (default 42; override via spec). The original `models` block
becomes the `from` field of a nested sample block — recursive resolution
handles the rest.

Load-bearing invariant: ALL other config fields (compile_kwargs, dynamo_flags,
modes, workers, timeout_s, pass_num, settings.*) come from the original config
verbatim. No stage may override anything except `models` and `name`.
"""
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUN_EXPERIMENT = REPO_ROOT / "tools" / "run_experiment.py"

# Stage configuration — the ONLY thing that varies across stages
STAGE_CONFIG = {
    "gate":   {"size": 5,  "name_suffix": "-gate"},
    "sample": {"size": 20, "name_suffix": "-sample"},
    "full":   {"size": None, "name_suffix": ""},  # None = no sub-sampling
}
DEFAULT_SUB_SAMPLE_SEED = 42


def derive_stage_config(orig_config: dict, stage: str, seed: int = DEFAULT_SUB_SAMPLE_SEED) -> dict:
    """Transform an experiment config for a stage (gate / sample / full).

    Only `models` and `name` change. Every other field (description, configs[],
    settings, etc.) is preserved verbatim.
    """
    if stage not in STAGE_CONFIG:
        raise ValueError(f"unknown stage {stage!r}; expected one of {list(STAGE_CONFIG)}")

    sc = STAGE_CONFIG[stage]
    new_config = json.loads(json.dumps(orig_config))  # deep copy
    new_config["name"] = orig_config["name"] + sc["name_suffix"]

    if sc["size"] is not None:
        # Sub-sample: wrap original models block in a sample resolver
        new_config["models"] = {
            "_comment": (f"Stage={stage} sub-sample (size={sc['size']}, seed={seed}). "
                         f"Original cohort preserved in 'from'. Generated by "
                         f"tools/derive_sweep_commands.py — DO NOT hand-edit; "
                         f"regenerate from {orig_config['name']} instead."),
            "source": "sample",
            "size": sc["size"],
            "seed": seed,
            "strategy": "random",
            "from": orig_config["models"],
        }
    # else: full stage — models block unchanged

    # Annotate that this is a derived config (not the source of truth)
    new_config["_derived_from"] = orig_config["name"]
    new_config["_derived_stage"] = stage

    return new_config


def emit_bash(transformed_config_path: Path, original_config: dict, stage: str) -> str:
    """Build the bash command that invokes run_experiment.py run on the
    transformed config. Includes the modellibs PYTHONPATH front-loading
    (run_experiment.py run doesn't auto-inject like sweep does).
    """
    stage_config = STAGE_CONFIG[stage]
    name = original_config["name"] + stage_config["name_suffix"]

    # Build PYTHONPATH from the config's modellibs hints if present.
    # Today the config doesn't have a pinning block; we fall back to the
    # transformers/diffusers in the abandoned NGB verify run's args. Caller can
    # override via --pythonpath. (Keeping this advisory — the user of the bash
    # is expected to have the right venv + PYTHONPATH already configured.)
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Stage: {stage}",
        f"# Derived from: {original_config['name']}",
        f"# Transformed config: {transformed_config_path}",
        "",
        f"cd {shlex.quote(str(REPO_ROOT))}",
        "",
        f"# Validate the transformed config before running",
        f"python3 {shlex.quote(str(RUN_EXPERIMENT))} validate {shlex.quote(str(transformed_config_path))}",
        "",
        f"# Run (use --workers/--timeout to override if needed)",
        f"python3 {shlex.quote(str(RUN_EXPERIMENT))} run {shlex.quote(str(transformed_config_path))}",
    ]
    return "\n".join(lines) + "\n"


def write_transformed_config(transformed: dict, stage: str, source_name: str) -> Path:
    """Write the transformed config to a deterministic /tmp path."""
    name = transformed["name"]
    out = Path(tempfile.gettempdir()) / f"{name}.json"
    out.write_text(json.dumps(transformed, indent=2) + "\n")
    return out


def validate_config(config_path: Path) -> tuple[int, str]:
    """Run run_experiment.py validate. Returns (returncode, combined output)."""
    r = subprocess.run(
        [sys.executable, str(RUN_EXPERIMENT), "validate", str(config_path)],
        capture_output=True, text=True,
    )
    return r.returncode, r.stdout + r.stderr


def main() -> int:
    if sys.version_info < (3, 9):
        sys.exit("ERROR: derive_sweep_commands.py requires Python >= 3.9")

    p = argparse.ArgumentParser(
        description="Derive gate/sample/full launch commands from an experiment config.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("config", type=Path, help="Path to experiment config JSON")
    p.add_argument("--stage", required=True, choices=list(STAGE_CONFIG),
                   help="Which stage to derive: gate (5 models), sample (20 models), or full")
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--validate", action="store_true",
                      help="Derive + validate the transformed config; do not emit or run")
    mode.add_argument("--emit", action="store_true",
                      help="Derive + write transformed config + print bash to stdout")
    mode.add_argument("--run", action="store_true",
                      help="Derive + write transformed config + execute the launch")
    p.add_argument("--seed", type=int, default=DEFAULT_SUB_SAMPLE_SEED,
                   help="Sub-sample seed (default: 42; deterministic per stage)")
    args = p.parse_args()

    if not args.config.is_file():
        sys.exit(f"ERROR: config not found: {args.config}")

    orig = json.loads(args.config.read_text())
    if "name" not in orig or "models" not in orig:
        sys.exit(f"ERROR: config missing required fields (name, models)")

    transformed = derive_stage_config(orig, args.stage, seed=args.seed)
    transformed_path = write_transformed_config(transformed, args.stage, orig["name"])

    print(f"[derive_sweep_commands] stage={args.stage} → {transformed_path}", file=sys.stderr)
    print(f"[derive_sweep_commands] derived name: {transformed['name']}", file=sys.stderr)

    rc, out = validate_config(transformed_path)
    if rc != 0:
        print(f"[derive_sweep_commands] VALIDATION FAILED on {transformed_path}", file=sys.stderr)
        print(out, file=sys.stderr)
        return 1
    print(f"[derive_sweep_commands] validated transformed config", file=sys.stderr)

    if args.validate:
        return 0

    bash = emit_bash(transformed_path, orig, args.stage)
    if args.emit:
        print(bash)
        return 0

    if args.run:
        print(f"[derive_sweep_commands] running stage={args.stage}...", file=sys.stderr)
        # Write bash to a tempfile + exec so the user sees the same command they'd
        # see with --emit. (Direct subprocess call would skip the validate step.)
        bash_path = Path(tempfile.gettempdir()) / f"{transformed['name']}.sh"
        bash_path.write_text(bash)
        bash_path.chmod(0o755)
        r = subprocess.run([str(bash_path)])
        return r.returncode

    return 0


if __name__ == "__main__":
    sys.exit(main())
