#!/bin/bash
# Restore script auto-generated by cleanup_modellibs_from_venvs.py.
# Reverses Phase 5 cleanup by re-installing the exact versions that were uninstalled.
# Note: re-installs go via pypi.org, which may BPF-block under agent identity for some pkgs.

set -e

HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-181552/bin/python3 -m pip install transformers==5.6.2
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-181552/bin/python3 -m pip install diffusers==0.37.1
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-nightly-cu126/bin/python3 -m pip install transformers==5.8.0.dev0
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-nightly-cu126/bin/python3 -m pip install diffusers==0.38.0
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-nightly-cu128/bin/python3 -m pip install transformers==5.6.2
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-nightly-cu128/bin/python3 -m pip install diffusers==0.37.1
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch-nightly-cu128/bin/python3 -m pip install timm==1.0.26
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch210/bin/python3 -m pip install transformers==5.4.0
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch210/bin/python3 -m pip install diffusers==0.37.1
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch210/bin/python3 -m pip install timm==1.0.26
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch211/bin/python3 -m pip install transformers==5.5.3
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch211/bin/python3 -m pip install diffusers==0.37.1
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch211/bin/python3 -m pip install timm==1.0.26
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch212-rc/bin/python3 -m pip install transformers==5.5.3
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch28/bin/python3 -m pip install transformers==5.4.0
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch28/bin/python3 -m pip install diffusers==0.37.1
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch29/bin/python3 -m pip install transformers==5.4.0
HTTP_PROXY=http://fwdproxy:8080 HTTPS_PROXY=http://fwdproxy:8080 /home/pengwu/envs/torch29/bin/python3 -m pip install diffusers==0.37.1
